require.config({
    urlArgs: "bust=1.73",
    waitSeconds: 15,
    paths: {
        jquery: "libs/jquery-1.11.2.min",
        slider: "libs/jquery.slider.min",
        formValidator: "libs/validator/formValidator",
        formValidatorRegex: "libs/validator/formValidatorRegex",
        transit: "libs/jquery.transit.min",
        layer: "libs/layer/layer.min",
        easie: "libs/jquery.easie.min",
        three: "libs/three.min",
        fancybox: "libs/fancybox/jquery.fancybox",
        fancybox_add: "libs/fancybox/fancybox_add",
        lazyload: "libs/jquery.lazyload",
        swiper: "libs/swiper.min",
        cycle: "libs/jquery.cycle.min",
        "jquery-ui": "libs/jquery-ui-1.11.4/jquery-ui",
        suggest: "libs/suggest",
        pagination: "libs/jk.pagination",
        lettering: "libs/jquery.lettering",
        textillate: "libs/jquery.textillate",
        zclip: "libs/jquery.zclip.min",
        jplayer: "libs/jplayer/jquery.jplayer.min"
    },
    shim: {
        slider: {deps: ["jquery"], exports: "slider"},
        formValidator: {deps: ["jquery"], exports: "formValidator"},
        formValidatorRegex: {deps: ["jquery"], exports: "formValidatorRegex"},
        transit: {deps: ["jquery"], exports: "transit"},
        layer: {deps: ["jquery"], exports: "jQuery.fn.layer"},
        easie: {deps: ["jquery"], exports: "jQuery.fn.easie"},
        three: {exports: "THREE"},
        lazyload: {deps: ["jquery"], exports: "jQuery.fn.lazyload"},
        cycle: {deps: ["jquery"], exports: "jQuery.fn.cycle"},
        fancybox: {deps: ["jquery"], exports: "jQuery.fn.fancybox"},
        fancybox_add: {deps: ["jquery"], exports: "fancybox_add"},
        "jquery-ui": {deps: ["jquery"], exports: "jQuery.fn.jquery-ui"},
        suggest: {deps: ["jquery"], exports: "jQuery.fn.suggest"},
        pagination: {deps: ["jquery"], exports: "jQuery.fn.pagination"},
        lettering: {deps: ["jquery"], exports: "jQuery.fn.lettering"},
        textillate: {deps: ["jquery"], exports: "jQuery.fn.textillate"},
        zclip: {deps: ["jquery"], exports: "jQuery.fn.zclip"},
        jplayer: {deps: ["jquery"], exports: "jQuery.fn.jplayer"}
    }
});
